# Generated by Django 6.0.3 on 2026-03-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_runner_alter_musician_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='editor',
            field=models.ForeignKey(default='tongue', on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='related editors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.musician', verbose_name='related artists'),
        ),
    ]
